In [1]:
import backtrader as bt
import pandas as pd
import numpy as np
# from get_score import get_score_ch
from sqlalchemy import create_engine
import talib as ta
import datetime
import pandas as pd

In [2]:
# indicators test
## import data
engine= create_engine('sqlite:///../../dataset/us/us_ticker_price_yf.db')
df = pd.read_sql('AAPL', engine)
df.rename(columns={'hgih':'high'},inplace=True)
df['chg_pct'] = ((df.close - df.open)/df.open)*100
df['close'] = df['close'].apply(lambda x: round(x,3))

In [3]:
df

open        high         low    close   Adj Close     volume  \
0        0.128348    0.128906    0.128348    0.128    0.100178  469033600   
1        0.122210    0.122210    0.121652    0.122    0.094952  175884800   
2        0.113281    0.113281    0.112723    0.113    0.087983  105728000   
3        0.115513    0.116071    0.115513    0.116    0.090160   86441600   
4        0.118862    0.119420    0.118862    0.119    0.092774   73449600   
...           ...         ...         ...      ...         ...        ...   
10480  145.259995  147.550003  145.000000  147.040  147.039993   64493200   
10481  145.669998  146.639999  143.779999  144.870  144.869995   63141600   
10482  145.759995  148.449997  145.050003  145.860  145.860001   77588800   
10483  142.990005  146.449997  142.119995  145.490  145.490005   71185600   
10484  144.080002  148.949997  143.250000  148.470  148.470001   77996900   

         datetime   chg_pct  
0      1980-12-12  0.000000  
1      1980-12-15 -0.456594  
2      1980-12-16 -0.492577  
3      1980-12-17  0.000000  
4      1980-12-18  0.000000  
...           ...       ...  
10480  2022-07-08  1.225388  
10481  2022-07-11 -0.549189  
10482  2022-07-12  0.068610  
10483  2022-07-13  1.748374  
10484  2022-07-14  3.046918  

[10485 rows x 8 columns]

In [4]:
periods = [10,20,50,150,200]
for period in periods:
    df['MA{}'.format(period)] = ta.SMA(df.close, timeperiod=period)


In [5]:
df

open        high         low    close   Adj Close     volume  \
0        0.128348    0.128906    0.128348    0.128    0.100178  469033600   
1        0.122210    0.122210    0.121652    0.122    0.094952  175884800   
2        0.113281    0.113281    0.112723    0.113    0.087983  105728000   
3        0.115513    0.116071    0.115513    0.116    0.090160   86441600   
4        0.118862    0.119420    0.118862    0.119    0.092774   73449600   
...           ...         ...         ...      ...         ...        ...   
10480  145.259995  147.550003  145.000000  147.040  147.039993   64493200   
10481  145.669998  146.639999  143.779999  144.870  144.869995   63141600   
10482  145.759995  148.449997  145.050003  145.860  145.860001   77588800   
10483  142.990005  146.449997  142.119995  145.490  145.490005   71185600   
10484  144.080002  148.949997  143.250000  148.470  148.470001   77996900   

         datetime   chg_pct     MA10      MA20      MA50       MA150  \
0      1980-12-12  0.000000      NaN       NaN       NaN         NaN   
1      1980-12-15 -0.456594      NaN       NaN       NaN         NaN   
2      1980-12-16 -0.492577      NaN       NaN       NaN         NaN   
3      1980-12-17  0.000000      NaN       NaN       NaN         NaN   
4      1980-12-18  0.000000      NaN       NaN       NaN         NaN   
...           ...       ...      ...       ...       ...         ...   
10480  2022-07-08  1.225388  141.351  138.2230  144.9494  161.237067   
10481  2022-07-11 -0.549189  141.672  138.3345  144.7154  161.111133   
10482  2022-07-12  0.068610  142.092  138.7710  144.3598  161.004600   
10483  2022-07-13  1.748374  142.897  139.4515  144.1166  160.872400   
10484  2022-07-14  3.046918  143.821  140.2370  143.9268  160.721000   

           MA200  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
...          ...  
10480  158.28875  
10481  158.28385  
10482  158.27900  
10483  158.27185  
10484  158.28735  

[10485 rows x 13 columns]

In [6]:
select = pd.DataFrame(columns=['ticker','conMA50','conMA200-trend','RSvalue','con52week-high','con52week-low'])
select

Empty DataFrame
Columns: [ticker, conMA50, conMA200-trend, RSvalue, con52week-high, con52week-low]
Index: []

In [7]:
df_length = len(df)

In [8]:
# con1,con2,con3,con4,con5 = 0,0,0,0,0
# if df.iloc[df_length-1].close > df.iloc[df_length-1].MA50 > df.iloc[df_length-1].MA150 > df.iloc[df_length-1].MA200:
#     con1 = 1
# if 

In [9]:
# find vcp
close_price = np.array(df.close)
close_price

array([1.2800e-01, 1.2200e-01, 1.1300e-01, ..., 1.4586e+02, 1.4549e+02,
       1.4847e+02])

In [10]:
import scipy.signal as sg

In [11]:
max_index = sg.argrelmax(close_price)

In [12]:
max_index

(array([   10,    13,    18, ..., 10474, 10480, 10482]),)

In [13]:
np.argmax(close_price),np.max(close_price)

(10352, 182.01)

In [14]:
df = df.tail(180)
df.index = range(len(df))

In [15]:
df

open        high         low   close   Adj Close     volume  \
0    149.330002  150.839996  149.009995  149.32  148.694199   60893400   
1    149.360001  149.729996  148.490005  148.85  148.226166   56094900   
2    149.820007  153.169998  149.720001  152.57  151.930588  100077900   
3    147.220001  149.940002  146.410004  149.80  149.172180  124953200   
4    148.990005  149.699997  147.800003  148.96  148.335709   74588300   
..          ...         ...         ...     ...         ...        ...   
175  145.259995  147.550003  145.000000  147.04  147.039993   64493200   
176  145.669998  146.639999  143.779999  144.87  144.869995   63141600   
177  145.759995  148.449997  145.050003  145.86  145.860001   77588800   
178  142.990005  146.449997  142.119995  145.49  145.490005   71185600   
179  144.080002  148.949997  143.250000  148.47  148.470001   77996900   

       datetime   chg_pct     MA10      MA20      MA50       MA150      MA200  
0    2021-10-26 -0.006693  147.021  144.4975  147.2054  138.639800  136.20800  
1    2021-10-27 -0.341453  147.815  144.7985  147.1786  138.828200  136.30825  
2    2021-10-28  1.835536  148.696  145.3520  147.3028  139.037267  136.41665  
3    2021-10-29  1.752481  149.192  145.7095  147.3648  139.226667  136.52110  
4    2021-11-01 -0.020135  149.433  146.2005  147.3802  139.420400  136.63020  
..          ...       ...      ...       ...       ...         ...        ...  
175  2022-07-08  1.225388  141.351  138.2230  144.9494  161.237067  158.28875  
176  2022-07-11 -0.549189  141.672  138.3345  144.7154  161.111133  158.28385  
177  2022-07-12  0.068610  142.092  138.7710  144.3598  161.004600  158.27900  
178  2022-07-13  1.748374  142.897  139.4515  144.1166  160.872400  158.27185  
179  2022-07-14  3.046918  143.821  140.2370  143.9268  160.721000  158.28735  

[180 rows x 13 columns]

In [16]:
close_price = np.array(df.close)

In [17]:
min1_val = np.min(close_price)
min1_ind = np.argmin(close_price)
min1_ind, min1_val

(161, 130.06)

In [18]:
max1_val = np.max(close_price[0:min1_ind])
max1_ind = np.argmax(close_price[0:min1_ind])

In [19]:
max1_val

182.01

In [20]:
dec_1 = (max1_val - min1_val) / max1_val
dec_1

0.28542387780891154

In [21]:
min2_ind = np.argmin(close_price[min1_ind+10:])
min2_val = np.min(close_price[min1_ind+10:])

In [22]:
close_price[min1_ind+1:]

array([131.56, 135.87, 135.35, 138.27, 141.66, 141.66, 137.44, 139.23,
       136.72, 138.93, 141.56, 142.92, 146.35, 147.04, 144.87, 145.86,
       145.49, 148.47])

In [23]:
min1_ind

161

In [24]:
min2_val,min2_ind

(138.93, 0)

In [25]:
min_index = sg.argrelmin(close_price)
min_index

(array([  1,   4,   7,   9,  12,  22,  27,  31,  34,  38,  43,  46,  50,
         55,  64,  67,  71,  75,  82,  86,  91,  95, 109, 112, 115, 119,
        123, 126, 128, 132, 134, 137, 139, 142, 145, 150, 152, 158, 161,
        164, 168, 170, 176, 178]),)

In [26]:
close_price[171:]

array([138.93, 141.56, 142.92, 146.35, 147.04, 144.87, 145.86, 145.49,
       148.47])

In [27]:
close_price[164]

135.35

In [28]:
df = pd.read_sql('INTC', engine)
df.rename(columns={'hgih':'high'},inplace=True)
df['chg_pct'] = ((df.close - df.open)/df.open)*100
df['close'] = df['close'].apply(lambda x: round(x,3))

In [29]:
df

open       high        low   close  Adj Close    volume  \
0       0.325521   0.330729   0.325521   0.326   0.192692  10924800   
1       0.325521   0.328125   0.322917   0.323   0.191150  17068800   
2       0.330729   0.335938   0.330729   0.331   0.195774  18508800   
3       0.330729   0.334635   0.329427   0.329   0.195004  11174400   
4       0.322917   0.322917   0.317708   0.318   0.188067  12172800   
...          ...        ...        ...     ...        ...       ...   
10668  37.660000  38.139999  37.389999  37.990  37.990002  22554800   
10669  37.660000  37.669998  37.029999  37.200  37.200001  25904300   
10670  37.650002  37.700001  36.990002  37.210  37.209999  30546300   
10671  36.680000  37.430000  36.619999  37.210  37.209999  27059200   
10672  36.990002  38.160000  36.290001  37.710  37.709999  36676700   

         datetime   chg_pct  
0      1980-03-17  0.000000  
1      1980-03-18 -0.799942  
2      1980-03-19  0.000000  
3      1980-03-20 -0.393677  
4      1980-03-21 -1.613117  
...           ...       ...  
10668  2022-07-08  0.876266  
10669  2022-07-11 -1.221453  
10670  2022-07-12 -1.168665  
10671  2022-07-13  1.444926  
10672  2022-07-14  1.946465  

[10673 rows x 8 columns]

In [30]:
df[df.datetime == '2019-09-12']

open       high    low  close  Adj Close    volume    datetime   chg_pct
9958  53.0  53.330002  52.07  53.01  49.371296  23308700  2019-09-12  0.018865

In [31]:
df = df[:9959]

In [32]:
df = df[9759:9959]

In [33]:
df.index = range(len(df))

In [34]:
close_price = np.array(df.close)

In [35]:
min1_ind = np.argmin(close_price)
min1_val = np.min(close_price)

In [36]:
min1_ind,min1_val

(128, 43.46)

In [37]:
close_price

array([47.45, 48.07, 48.86, 47.7 , 49.31, 50.13, 47.75, 48.37, 46.24,
       47.21, 47.38, 47.83, 48.29, 47.86, 47.08, 47.74, 45.57, 45.54,
       44.84, 43.59, 46.19, 46.36, 46.75, 46.93, 47.08, 44.49, 47.22,
       47.44, 47.74, 48.01, 48.56, 48.93, 48.35, 48.6 , 48.13, 48.47,
       49.19, 48.27, 47.94, 49.76, 47.04, 46.71, 46.54, 47.54, 47.12,
       48.73, 49.22, 50.01, 49.9 , 49.23, 48.84, 48.77, 50.01, 50.47,
       50.81, 51.66, 51.4 , 51.39, 51.41, 52.49, 53.1 , 53.23, 53.24,
       52.96, 53.3 , 53.94, 53.68, 52.95, 52.6 , 52.48, 53.35, 53.57,
       54.37, 53.44, 54.33, 54.1 , 54.17, 53.82, 54.64, 53.26, 52.78,
       53.44, 53.16, 53.11, 53.7 , 54.51, 54.36, 55.48, 55.92, 55.6 ,
       55.68, 55.32, 55.75, 55.8 , 56.42, 56.28, 56.71, 58.56, 58.49,
       58.82, 58.78, 58.72, 57.61, 52.43, 51.11, 51.04, 50.76, 50.55,
       51.75, 51.22, 50.48, 49.24, 46.62, 46.2 , 44.76, 45.17, 45.62,
       45.53, 44.89, 43.56, 44.46, 44.  , 44.53, 44.57, 43.57, 44.23,
       44.73, 44.04,

In [38]:
df.iloc[min1_ind]

open              44.25
high              44.59
low           43.200001
close             43.46
Adj Close     40.205376
volume         31155700
datetime     2019-06-03
chg_pct       -1.785313
Name: 128, dtype: object

In [39]:
max1_ind = np.argmax(close_price[0:min1_ind])
max1_val = np.max(close_price[0:min1_ind])

In [40]:
max1_ind, max1_val

(99, 58.82)

In [41]:
df.iloc[max1_ind]

open          58.150002
high          58.830002
low           57.880001
close             58.82
Adj Close     54.083878
volume         12327500
datetime     2019-04-22
chg_pct        1.152189
Name: 99, dtype: object

In [42]:
dec_1 = (max1_val - min1_val) / max1_val
dec_1

0.2611356681400884

In [43]:
df

open       high        low  close  Adj Close    volume    datetime  \
0    47.270000  47.459999  46.700001  47.45  43.354565  20723000  2018-11-26   
1    46.939999  48.220001  46.590000  48.07  43.921059  27621000  2018-11-27   
2    47.939999  48.880001  47.650002  48.86  44.642876  28003200  2018-11-28   
3    48.490002  48.560001  47.630001  47.70  43.582989  23592500  2018-11-29   
4    47.950001  49.320000  47.560001  49.31  45.054031  43313700  2018-11-30   
..         ...        ...        ...    ...        ...       ...         ...   
195  50.250000  50.990002  50.070000  50.92  47.424763  17067900  2019-09-06   
196  51.060001  52.029999  51.020000  51.59  48.048771  20749700  2019-09-09   
197  51.330002  51.840000  50.830002  51.82  48.262981  18532000  2019-09-10   
198  51.599998  52.790001  51.380001  52.79  49.166405  18968900  2019-09-11   
199  53.000000  53.330002  52.070000  53.01  49.371296  23308700  2019-09-12   

      chg_pct  
0    0.380792  
1    2.407331  
2    1.919070  
3   -1.629204  
4    2.836289  
..        ...  
195  1.333330  
196  1.037992  
197  0.954603  
198  2.306206  
199  0.018865  

[200 rows x 8 columns]

In [44]:
min2_ind = np.argmin(close_price[min1_ind+7:])
min2_val = np.min(close_price[min1_ind+7:])

In [45]:
close_price[min1_ind+7:]

array([46.32, 46.7 , 46.19, 46.13, 47.37, 47.07, 47.19, 47.46, 47.63,
       46.85, 48.19, 47.46, 47.87, 48.05, 48.12, 48.52, 48.08, 47.82,
       47.75, 48.21, 48.6 , 49.92, 50.12, 49.17, 49.39, 49.94, 50.27,
       51.35, 51.75, 52.92, 52.16, 51.59, 52.51, 51.7 , 50.55, 49.5 ,
       48.68, 46.97, 46.96, 46.73, 47.17, 45.98, 45.6 , 46.84, 45.87,
       45.7 , 46.5 , 47.23, 46.6 , 47.15, 46.78, 44.96, 45.56, 45.79,
       45.79, 46.87, 47.41, 46.98, 48.92, 50.1 , 50.92, 51.59, 51.82,
       52.79, 53.01])

In [46]:
min2_ind = min2_ind + min1_ind + 7

In [47]:
df.iloc[min2_ind]

open          46.349998
high          46.630001
low           44.799999
close             44.96
Adj Close     41.873863
volume         32814000
datetime     2019-08-23
chg_pct        -2.99892
Name: 186, dtype: object

In [48]:
max2_ind = np.argmax(close_price[min1_ind:min2_ind])
max2_val = np.max(close_price[min1_ind:min2_ind])

In [49]:
max2_ind,max2_val

(36, 52.92)

In [50]:
dec_2 = (max2_val -min2_val) / max2_val

In [51]:
dec_2

0.15041572184429328

In [52]:
min3_ind = np.argmin(close_price[min2_ind+3:])
min3_val = np.min(close_price[min2_ind+3:])

In [53]:
min3_ind,min3_val

(0, 45.79)

In [54]:
close_price[min2_ind+3:]

array([45.79, 46.87, 47.41, 46.98, 48.92, 50.1 , 50.92, 51.59, 51.82,
       52.79, 53.01])

In [55]:
# 判断是不是前后5天的极值点

In [56]:
df.close.rolling(window=10).min()

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
       ...  
195    44.96
196    45.56
197    45.79
198    45.79
199    46.87
Name: close, Length: 200, dtype: float64

In [57]:
df_length = len(df)

In [58]:
df_length

200

In [59]:
df_length

200

In [60]:
df['extremum'] = 0
for i in range(5,df_length):
    if df.close.loc[i] == df.close.loc[i-5:i+5].min() or df.close.loc[i] == df.close.loc[i-5:i+5].max() :
        df['extremum'].loc[i] = 1

/var/folders/lz/kp_y7_p51sbc8gskvwtst_6h0000gp/T/ipykernel_11636/3506821763.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['extremum'].loc[i] = 1


In [61]:
index_arr = np.array(df[df.extremum == 1].index)
close_arr = np.array(df[df.extremum == 1].close)

In [62]:
close_arr

array([50.13, 46.24, 43.59, 44.49, 49.76, 46.54, 50.01, 48.77, 53.94,
       52.48, 54.37, 54.64, 52.78, 55.92, 58.82, 43.56, 43.46, 46.13,
       46.85, 47.75, 52.92, 45.6 , 47.23, 44.96, 53.01])

In [63]:
index_arr

array([  5,   8,  19,  25,  39,  42,  47,  51,  65,  69,  72,  78,  80,
        88,  99, 119, 128, 138, 144, 153, 164, 177, 182, 186, 199])

In [64]:
min1_val = np.min(close_arr)
min1_ind = np.argmin(close_arr)

In [65]:
min1_ind, min1_val

(16, 43.46)

In [66]:
max1_val = np.max(close_arr[:min1_ind])
max1_ind = index_arr[np.argmax(close_arr[:min1_ind])]

In [67]:
max1_ind, max1_val

(99, 58.82)

In [68]:
close_arr[min1_ind:]

array([43.46, 46.13, 46.85, 47.75, 52.92, 45.6 , 47.23, 44.96, 53.01])

In [69]:
min2_val = np.min(close_arr[min1_ind+1:])
min2_ind = np.argmin(close_arr[min1_ind+1:]) + min1_ind + 1

In [70]:
min2_ind, min2_val

(23, 44.96)

In [71]:
max2_val = np.max(close_arr[min1_ind:min2_ind])
max2_ind = np.argmax(close_arr[min1_ind:min2_ind]) + min1_ind

In [72]:
close_arr[min1_ind:min2_ind]

array([43.46, 46.13, 46.85, 47.75, 52.92, 45.6 , 47.23])

In [73]:
index_arr[min1_ind:min2_ind]

array([128, 138, 144, 153, 164, 177, 182])

In [74]:
df.iloc[164]

open              51.98
high          52.970001
low           51.799999
close             52.92
Adj Close      48.95694
volume         20896400
datetime     2019-07-24
chg_pct        1.808385
extremum              1
Name: 164, dtype: object

In [75]:
max2_ind

20

In [76]:
index_arr[max2_ind]

164

In [77]:
min2_ind

23

In [78]:
len(close_arr)

25

In [79]:
df.iloc[177]

open          45.759998
high              46.07
low           45.439999
close              45.6
Adj Close     42.469936
volume         18494300
datetime     2019-08-12
chg_pct        -0.34965
extremum              1
Name: 177, dtype: object

In [80]:
df[df.datetime=='2019-08-23']

open       high        low  close  Adj Close    volume    datetime  \
186  46.349998  46.630001  44.799999  44.96  41.873863  32814000  2019-08-23   

     chg_pct  extremum  
186 -2.99892         1

In [81]:
df.iloc[199]

open               53.0
high          53.330002
low               52.07
close             53.01
Adj Close     49.371296
volume         23308700
datetime     2019-09-12
chg_pct        0.018865
extremum              1
Name: 199, dtype: object

In [2]:
import pandas as pd
res = pd.DataFrame([['name','date',0,0,0]],columns=['ticker','datetime','vcp','cup','db'])
res

ticker datetime  vcp  cup  db
0   name     date    0    0   0